In [1]:
using JuMP, CSV, DataFrames, Gurobi, LinearAlgebra

In [2]:
materias = CSV.File("C://Users//Acer//Desktop//nao-linear//proj1_final//materias1.csv")
lista_materias = DataFrame(materias)

460×8 DataFrame. Omitted printing of 4 columns
│ Row │ Matéria                    │ 7h30-9h30 │ 9h30-11h30 │ 13h30-15h30 │
│     │ Union{Missing, String}     │ Int64     │ Int64      │ Int64       │
├─────┼────────────────────────────┼───────────┼────────────┼─────────────┤
│ 1   │ Álgebra Linear A           │ 2         │ 0          │ 0           │
│ 2   │ missing                    │ 0         │ 0          │ 0           │
│ 3   │ missing                    │ 2         │ 0          │ 0           │
│ 4   │ missing                    │ 0         │ 0          │ 0           │
│ 5   │ missing                    │ 0         │ 0          │ 0           │
│ 6   │ Álgebra Linear B           │ 2         │ 0          │ 0           │
│ 7   │ missing                    │ 0         │ 0          │ 0           │
│ 8   │ missing                    │ 2         │ 0          │ 0           │
│ 9   │ missing                    │ 0         │ 0          │ 0           │
│ 10  │ missing                    │ 0         │ 0          │ 0           │
⋮
│ 450 │ missing                    │ 0         │ 0          │ 0           │
│ 451 │ Cálculo com Álgebra Linear │ 0         │ 0          │ 0           │
│ 452 │ missing                    │ 0         │ 0          │ 0           │
│ 453 │ missing                    │ 0         │ 0          │ 0           │
│ 454 │ missing                    │ 0         │ 0          │ 0           │
│ 455 │ missing                    │ 0         │ 0          │ 0           │
│ 456 │ Cálculo com Álgebra Linear │ 0         │ 0          │ 0           │
│ 457 │ missing                    │ 0         │ 0          │ 0           │
│ 458 │ missing                    │ 0         │ 0          │ 0           │
│ 459 │ missing                    │ 0         │ 0          │ 0           │
│ 460 │ missing                    │ 0         │ 0          │ 0           │

In [3]:
Professores = CSV.File("C://Users//Acer//Desktop//nao-linear//proj1_final//preferenciasProfes1.csv")
lista_professores = DataFrame(Professores)

52×93 DataFrame. Omitted printing of 87 columns
│ Row │ materias        │ CM005 A │ CM005 B │ CM005 C │ CM005 D │ CM005 E │
│     │ String          │ Int64   │ Int64   │ Int64   │ Int64   │ Int64   │
├─────┼─────────────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ 1   │ Abel            │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 2   │ Ademir          │ 0       │ 0       │ 5       │ 5       │ 5       │
│ 3   │ Adonai          │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 4   │ Adriana         │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 5   │ Aillin          │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 6   │ Aldemir         │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 7   │ Ana Gabriela    │ 5       │ 5       │ 0       │ 0       │ 0       │
│ 8   │ Barreda         │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 9   │ Carlos Henrique │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 10  │ Carlos Vianna   │ 0       │ 0       │ 0       │ 0       │ 0       │
⋮
│ 42  │ Pedro           │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 43  │ Raul            │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 44  │ Roberto         │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 45  │ Rodrigo         │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 46  │ Rossetto        │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 47  │ Saulo           │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 48  │ Tanise          │ 2       │ 2       │ 0       │ 0       │ 0       │
│ 49  │ Trovon          │ 0       │ 0       │ 2       │ 2       │ 2       │
│ 50  │ Ximena          │ 0       │ 0       │ 2       │ 2       │ 2       │
│ 51  │ Yuan            │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 52  │ Zeca            │ 0       │ 0       │ 0       │ 0       │ 0       │

In [4]:
DU = zeros(5,7,92);
for k=1:92
    DU[:,:,k] .= lista_materias[1 + (k-1) * 5: 5 + (k-1) * 5, 2:8]
end

In [5]:
HT = copy(DU)
HT = HT/2;

In [6]:
preferencias = zeros(Int,52,92);
preferencias .= lista_professores[:,2:93];
# preferencias = 10 * preferencias;

In [7]:
dias = CSV.File("C://Users//Acer//Desktop//nao-linear//proj1_final//V.csv")
dias_aulas = DataFrame(dias)

5×93 DataFrame. Omitted printing of 87 columns
│ Row │ materias      │ CM005 A │ CM005 B │ CM005 C │ CM005 D │ CM005 E │
│     │ String        │ Int64   │ Int64   │ Int64   │ Int64   │ Int64   │
├─────┼───────────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ 1   │ segunda feira │ 1       │ 1       │ 0       │ 0       │ 0       │
│ 2   │ terça feira   │ 0       │ 0       │ 1       │ 1       │ 1       │
│ 3   │ quarta feira  │ 1       │ 1       │ 0       │ 0       │ 0       │
│ 4   │ quinte feira  │ 0       │ 0       │ 1       │ 1       │ 1       │
│ 5   │ sexta feira   │ 0       │ 0       │ 0       │ 0       │ 0       │

In [8]:
V = dias_aulas[1:5,2:93]

5×92 DataFrame. Omitted printing of 85 columns
│ Row │ CM005 A │ CM005 B │ CM005 C │ CM005 D │ CM005 E │ CM005 F │ CM005 G │
│     │ Int64   │ Int64   │ Int64   │ Int64   │ Int64   │ Int64   │ Int64   │
├─────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ 1   │ 1       │ 1       │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 2   │ 0       │ 0       │ 1       │ 1       │ 1       │ 1       │ 1       │
│ 3   │ 1       │ 1       │ 0       │ 0       │ 0       │ 0       │ 0       │
│ 4   │ 0       │ 0       │ 1       │ 1       │ 1       │ 1       │ 1       │
│ 5   │ 0       │ 0       │ 0       │ 0       │ 0       │ 0       │ 0       │

In [9]:
model = Model(Gurobi.Optimizer)

P = size(preferencias,1) # número de professores
M = size(preferencias,2) # número de matérias
H = 7 # horarios
D = 5 # dias

Academic license - for non-commercial use only - expires 2021-01-09


5

In [10]:
@variable(model, x[1:P, 1:M] ≥ 0, Bin) #P*M var de decisão

52×92 Array{VariableRef,2}:
 x[1,1]   x[1,2]   x[1,3]   x[1,4]   x[1,5]   …  x[1,90]   x[1,91]   x[1,92]
 x[2,1]   x[2,2]   x[2,3]   x[2,4]   x[2,5]      x[2,90]   x[2,91]   x[2,92]
 x[3,1]   x[3,2]   x[3,3]   x[3,4]   x[3,5]      x[3,90]   x[3,91]   x[3,92]
 x[4,1]   x[4,2]   x[4,3]   x[4,4]   x[4,5]      x[4,90]   x[4,91]   x[4,92]
 x[5,1]   x[5,2]   x[5,3]   x[5,4]   x[5,5]      x[5,90]   x[5,91]   x[5,92]
 x[6,1]   x[6,2]   x[6,3]   x[6,4]   x[6,5]   …  x[6,90]   x[6,91]   x[6,92]
 x[7,1]   x[7,2]   x[7,3]   x[7,4]   x[7,5]      x[7,90]   x[7,91]   x[7,92]
 x[8,1]   x[8,2]   x[8,3]   x[8,4]   x[8,5]      x[8,90]   x[8,91]   x[8,92]
 x[9,1]   x[9,2]   x[9,3]   x[9,4]   x[9,5]      x[9,90]   x[9,91]   x[9,92]
 x[10,1]  x[10,2]  x[10,3]  x[10,4]  x[10,5]     x[10,90]  x[10,91]  x[10,92]
 x[11,1]  x[11,2]  x[11,3]  x[11,4]  x[11,5]  …  x[11,90]  x[11,91]  x[11,92]
 x[12,1]  x[12,2]  x[12,3]  x[12,4]  x[12,5]     x[12,90]  x[12,91]  x[12,92]
 x[13,1]  x[13,2]  x[13,3]  x[13,4]  x[13,5] 

In [11]:
@constraint(model,[p=1:P, d=1:D, h=1:H], sum(HT[d, h, t] * x[p,t] for t=1:M) ≤ 1)
@constraint(model, [t=1:M], sum(x[p,t] for p=1:P) == 1)
@constraint(model, [p=1:P], sum(DU[d, h, t]*x[p,t] for t=1:M, d=1:D, h=1:H) ≥ 6)
@constraint(model, [p=1:P], sum(DU[d, h, t]*x[p,t] for t=1:M, d=1:D, h=1:H) ≤ 12);

In [12]:
# Primeiro maximizando o modelo
@objective(model, Max, sum(preferencias[p,t]*x[p,t] for p=1:P, t=1:M) - sum(x[p,t]*x[p,i]*(norm(V[t] - V[i]))^2 for p=1:P, t=1:M, i=1:M));


In [13]:
optimize!(model) #resolver

Gurobi Optimizer version 9.1.0 build v9.1.0rc0 (win64)
Thread count: 4 physical cores, 4 logical processors, using up to 4 threads
Optimize a model with 2016 rows, 4784 columns and 25168 nonzeros
Model fingerprint: 0xd943c4a8
Model has 171028 quadratic objective terms
Variable types: 0 continuous, 4784 integer (4784 binary)
Coefficient statistics:
  Matrix range     [1e+00, 8e+00]
  Objective range  [1e+00, 5e+00]
  QObjective range [4e+00, 2e+01]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+01]
Found heuristic solution: objective -211.0000000
Presolve removed 520 rows and 0 columns
Presolve time: 0.31s
Presolved: 4408 rows, 7696 columns, 199576 nonzeros
Variable types: 0 continuous, 7696 integer (4784 binary)

Root relaxation: objective -3.429590e+02, 873 iterations, 0.09 seconds

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0  342.95897    0   74 -21

In [14]:
resp = value.(x)
resp

52×92 Array{Float64,2}:
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0  …  -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0   1.0  -0.0     -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0     -0.0   0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0     -0.0  -0.0   1.0   1.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0     -0.0   0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0  …  -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
  1.0  -0.0  -0.0  -0.0  -0.0  -0.0     -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0     -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0     -0.0   0.0  -0.0  -0.0   1.0   1.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0      1.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0  …  -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0     -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 -0.0  -0.0  -0.0  -0.0  -0.0  -0.0     -0.0  -0.0  -0.0  -0.0  -0.0  -0.0
 

In [15]:
sum(resp, dims=1)

1×92 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  …  1.0  1.0  1.0  1.0  1.0  1.0  1.0

In [16]:
# média da do grau de  satisfação
sum(sum(resp .* preferencias, dims=2)) / 52

5.9423076923076925

In [17]:
# satisfação individual
exe=sum(resp .* preferencias, dims=2)

52×1 Array{Float64,2}:
 8.0
 9.0
 0.0
 9.0
 4.0
 4.0
 5.0
 9.0
 0.0
 3.0
 4.0
 9.0
 5.0
 ⋮
 0.0
 8.0
 5.0
 7.0
 7.0
 4.0
 7.0
 9.0
 2.0
 9.0
 9.0
 5.0

In [18]:
show(IOContext(stdout, :limit=>false), MIME"text/plain"(), resp[47,:])
#prof 47 recebeu as disciplina 85 e 86 de 3h30min-tudo certo!

92-element Array{Float64,1}:
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
  0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
  1.0
  1.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0
 -0.0

In [19]:
A = value.(x) .* preferencias
findall(A .== 1)

1-element Array{CartesianIndex{2},1}:
 CartesianIndex(16, 64)

In [20]:
# concl = DataFrame(resp);
# show(IOContext(stdout, :limit=>false), MIME"text/plain"(), resp);

In [21]:
sum(exe)

309.0